@bank_backend_CSharp_HostAddress = http://localhost:5292

GET {{bank_backend_CSharp_HostAddress}}/users
Accept: application/json

Post {{bank_backend_CSharp_HostAddress}}/users
Content-Type: application/json

{  
   
   "Email": "pedro@teste.com",
   "Name": "Pedro",
   "Password": "1234",
   "Telefone": "62997758544",
   "Cpf": "187574571-9"
   
}

###
Post {{bank_backend_CSharp_HostAddress}}/login
Content-Type: application/json

{
    "Email": "nadielly@teste.com",
    "Password": "1234"
}


###
GET {{bank_backend_CSharp_HostAddress}}/conta/4
Accept: application/json


###
GET {{bank_backend_CSharp_HostAddress}}/users/4
Accept: application/json

###

GET {{bank_backend_CSharp_HostAddress}}/transacoes/4
Accept: application/json

###
Post {{bank_backend_CSharp_HostAddress}}/transacoes
Content-Type: application/json

{
   "Valor": 1000.00,
   "DirecaoTransacao": "SAIDA",
   "TipoTransacao": "SAQUE",
   "UserId": 23,
   "NumeroContaDestino":100002 ,
   "NumeroContaOrigem": 100003,
  "Historico": ""  
}


###
GET  {{bank_backend_CSharp_HostAddress}}/login/logout/4
Content-Type: application/json


###
DELETE {{bank_backend_CSharp_HostAddress}}/users/delete/7
Accept: application/json

